### ISSUE TITLE
Link to a jar download?

### ISSUE THREAD

**Issue by K4N0** [spacebuilder2020/Random_Enderio_Addons#1]
is there a link to download the jar file yet? I'd love to check it out.
I could even do a mod showcase on it.

Modpack Location:
http://www.technicpack.net/modpack/mojangsters.583708

Latest Youtube Video
https://www.youtube.com/watch?v=H1WKgGrWjug

Youtube Channel
https://www.youtube.com/channel/UCVRDbrSypbA696FHcaiBhkg

**Comment by spacebuilder2020** [comment]
Currently, I am waiting for enderio to modify it's conduit network code so, it won't crash without a modified class.  As a result, until that is complete, the mod will crash when you place down an item.

Once that is complete, I will post a jar file.

**Comment by spacebuilder2020** [comment]
I have released a working binary.  It requires an in-production version (2.3.0.420_beta) of ender-io, so you will have to build right now.
